name: TaskManageSiteService
description: DBMS Final Proejct, using Dart for hosting a website

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# HTTP server relies on database methods that in turn depends on mysql1 package
dependencies:
  mysql1: ^0.17.1

